"""add last_synced_at columns

Revision ID: 27b80cb31a46
Revises: 46fdece1199a
Create Date: 2026-05-18 12:31:17.804717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b80cb31a46'
down_revision: Union[str, Sequence[str], None] = '46fdece1199a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_accounts', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('wishes', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'last_synced_at')
    op.drop_column('game_accounts', 'last_synced_at')
    # ### end Alembic commands ###
