"""initial schema

Revision ID: 46fdece1199a
Revises: 
Create Date: 2026-05-18 01:34:25.806679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fdece1199a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('game_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('server', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ar', sa.Integer(), nullable=True),
    sa.Column('wl', sa.String(), nullable=True),
    sa.Column('mc_option', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_accounts_game_id'), 'game_accounts', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_accounts_id'), 'game_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_game_accounts_uid'), 'game_accounts', ['uid'], unique=False)
    op.create_table('user_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_oauth_id'), 'user_oauth', ['id'], unique=False)
    op.create_table('wishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wish_uid', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('gacha_type', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('banner_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['game_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishes_id'), 'wishes', ['id'], unique=False)
    op.create_index(op.f('ix_wishes_wish_uid'), 'wishes', ['wish_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishes_wish_uid'), table_name='wishes')
    op.drop_index(op.f('ix_wishes_id'), table_name='wishes')
    op.drop_table('wishes')
    op.drop_index(op.f('ix_user_oauth_id'), table_name='user_oauth')
    op.drop_table('user_oauth')
    op.drop_index(op.f('ix_game_accounts_uid'), table_name='game_accounts')
    op.drop_index(op.f('ix_game_accounts_id'), table_name='game_accounts')
    op.drop_index(op.f('ix_game_accounts_game_id'), table_name='game_accounts')
    op.drop_table('game_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
